name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: aosc/aosc-os
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Install Dependency
      run: |
        sudo apt update
        sudo apt-get install -y opencc
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
