name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Install Dependency
      run: |
        wget https://launchpad.net/ubuntu/+archive/primary/+files/opencc_1.1.1+git20200624+ds2-10ubuntu2_amd64.deb
        wget https://launchpad.net/ubuntu/+archive/primary/+files/libopencc1.1_1.1.1+git20200624+ds2-10ubuntu2_amd64.deb
        wget https://launchpad.net/ubuntu/+archive/primary/+files/libopencc-data_1.1.1+git20200624+ds2-10ubuntu2_all.deb
        sudo apt-get install -y libmarisa0 \
          ./libopencc-data_1.1.1+git20200624+ds2-10ubuntu2_all.deb \
          ./libopencc1.1_1.1.1+git20200624+ds2-10ubuntu2_amd64.deb \
          ./opencc_1.1.1+git20200624+ds2-10ubuntu2_amd64.deb
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
