name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: aosc/aosc-os-buildkit
    steps:
    - name: Install Dependency
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
        apt update
        apt-get install -y opencc
    - uses: actions/checkout@v2
    - name: Build
      run: |
      export PATH=$HOME/.cargo/bin:$PATH
      cargo build
    - name: Test
      run: cargo test
