name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Install Dependency
      run: sudo apt update && sudo apt install -y opencc libssl-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
