name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: aosc/aosc-os-buildkit
    steps:
    - name: Install Dependency
      run: |
        apt update
        apt-get install -y rustc opencc
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
