name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Install Dependency
      run: wget http://launchpadlibrarian.net/530734693/opencc_1.1.1+git20200624+ds2-10ubuntu2_amd64.deb && apt-get install -y ./opencc_1.1.1+git20200624+ds2-10ubuntu2_amd64.deb 
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
